SELECT
    HOUR(DATETIME) AS HOUR,
    COUNT(*) AS COUNT
FROM
    ANIMAL_OUTS
WHERE
    HOUR(DATETIME) BETWEEN '9' AND '19'
GROUP BY
    HOUR(DATETIME)
ORDER BY
    HOUR(DATETIME) ASC

### WHERE 절 말고 HAVING 으로도 가능하다.
GROUP BY
    HOUR(DATETIME)
HAVING
    HOUR BETWEEN '9' AND '19'
ORDER BY
    HOUR(DATETIME) ASC