SELECT WAREHOUSE_ID, 
       WAREHOUSE_NAME, 
       ADDRESS,
       IF(FREEZER_YN IS NOT NULL,FREEZER_YN,'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS like '%경기도%'
ORDER BY WAREHOUSE_ID

-- 코드를 입력하세요
SELECT  WAREHOUSE_ID,
        WAREHOUSE_NAME, 
        ADDRESS, 
        IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID ASC

SELECT WAREHOUSE_ID, 
       WAREHOUSE_NAME,
       ADDRESS,
       COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE 
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID ASC;

### 함수
IFNULL(칼럼명, '임의출력값') = NULL 값을 다른 값으로 바꾸어주는 함수
COALESCE(컬럼명, '임의출력값') = NULL 값을 다른 값으로 바꾸어주는 함수

