SELECT DATETIME AS '시간'
FROM ANIMAL_INS
WHERE DATETIME = (
    SELECT max(DATETIME)
    FROM ANIMAL_INS)

# 간단하게 아래처럼 할 수 있음.
SELECT MAX(DATETIME) AS '시간' FROM ANIMAL_INS


### 간단하게 ORDEY BY와 LIMIT 함수로 풀면 아래와 같다.
SELECT DATETIME AS '시간'
FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1